set(LUAJIT_COMPILE_FLAGS -O2 -fomit-frame-pointer -fno-stack-protector -Wall -fPIC -Wno-shorten-64-to-32)
set(LUAJIT_COMPILE_DEFINES -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DLUAJIT_UNWIND_EXTERNAL -DLUAJIT_OS=LUAJIT_OS_OSX)
set(LUAJIT_COMPILE_DEFINES_DYNAMIC -shared)

set(LUAJIT_VM_MODE machasm)

if(LUAJIT_TARGET_ARCH STREQUAL "x64")
    set(DASM_FLAGS -D JIT -D FFI -D ENDIAN_LE -D FPU -D HFABI -D P64)
    set(DASC_FILE ${LUAJIT_ROOT_FOLDER}/src/vm_x64.dasc)
elseif(LUAJIT_TARGET_ARCH STREQUAL "arm64")
    set(DASM_FLAGS -D JIT -D FFI -D ENDIAN_LE -D FPU -D HFABI -D DUALNUM -D P64)
    set(DASC_FILE ${LUAJIT_ROOT_FOLDER}/src/vm_arm64.dasc)
endif()
