set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_VERSION "10.0")

set(CMAKE_GENERATOR_PLATFORM "ARM")
set(CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE "x64")

set(CMAKE_C_COMPILER "cl")

set(LUAJIT_TARGET_ARCH "arm32")
