if(NOT LUAJIT_TARGET_ARCH STREQUAL "")
    return()
endif()

if(WIN32)
    if(CMAKE_VS_PLATFORM_NAME MATCHES "^(x86|Win32)$")
        set(LUAJIT_TARGET_ARCH "x86")
    elseif(CMAKE_VS_PLATFORM_NAME MATCHES "^x64$")
        set(LUAJIT_TARGET_ARCH "x64")
    elseif(CMAKE_VS_PLATFORM_NAME MATCHES "^ARM$")
        set(LUAJIT_TARGET_ARCH "arm32")
    elseif(CMAKE_VS_PLATFORM_NAME MATCHES "^ARM64$")
        set(LUAJIT_TARGET_ARCH "arm64")
    else()
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(i.86|x86)$")
            set(LUAJIT_TARGET_ARCH "x86")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|x64)$")
            set(LUAJIT_TARGET_ARCH "x64")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(armv7|arm)$")
            set(LUAJIT_TARGET_ARCH "arm32")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
            set(LUAJIT_TARGET_ARCH "arm64")
        endif()
    endif()
elseif(LINUX)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(i.86|x86)$")
        set(LUAJIT_TARGET_ARCH "x86")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64)$")
        set(LUAJIT_TARGET_ARCH "x64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(armv[6-9]|arm|armhf)$")
        set(LUAJIT_TARGET_ARCH "arm32")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
        set(LUAJIT_TARGET_ARCH "arm64")
    endif()
elseif(APPLE)
    if(CMAKE_OSX_ARCHITECTURES MATCHES "^x86_64$")
        set(LUAJIT_TARGET_ARCH "x64")
    elseif(CMAKE_OSX_ARCHITECTURES MATCHES "^arm64$")
        set(LUAJIT_TARGET_ARCH "arm64")
    else()
        if(CMAKE_SYSTEM_PROCESSOR MATCHES "^x86_64$")
            set(LUAJIT_TARGET_ARCH "x64")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(arm64|aarch64)$")
            set(LUAJIT_TARGET_ARCH "arm64")
        endif()
    endif()
endif()
